spring.ai.openai.api-key=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

spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.2







