spring.application.name=demo
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-3.5-turbo
spring.ai.openai.moderation.model=text-moderation-stable
